# Generated by Django 5.0.6 on 2024-07-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_patients_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='age',
            new_name='idade',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='escolaridade',
            field=models.CharField(choices=[('INFANTIL', 'Educação Infantil (Pré-escola'), ('EF1', 'Ensino Fundamental I'), ('EF2', 'Ensino Fundamental II'), ('MEDIO', 'Ensino Médio'), ('TECNICO', 'Ensino Técnico e Profissionalizante'), ('SUPERIOR_INCOMPLETO', 'Ensino Superior Incompleto'), ('SUPERIOR_COMPLETO', 'Ensino Superior Completo'), ('POS_GRADUACAO', 'Pós-Graduação'), ('POS_DOUTORADO', 'Pós-Doutorado'), ('N/A', 'Não Aplicável')], default='N/A', max_length=25),
        ),
        migrations.AddField(
            model_name='patient',
            name='nome',
            field=models.CharField(default='Default name', max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='nucleos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='religiao',
            field=models.CharField(choices=[('C', 'Cristianismo'), ('I', 'Islamismo'), ('H', 'Hinduísmo'), ('B', 'Budismo'), ('J', 'Judaísmo'), ('E', 'Espiritismo'), ('T', 'Taioísmo'), ('A', 'Ateísmo'), ('O', 'Outra'), ('N', 'Não Aplicável')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não Aplicável')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='trabalho',
            field=models.CharField(default='', max_length=70),
        ),
    ]
