export { default as IdentificationDataForm } from './IdentificationDataForm'
export { default as NavBar } from './NavBar'
export { default as PatientTable } from './PatientTable'
export { default as Register } from './Register'
export { default as Login } from './Login'